# Generated by Django 6.0 on 2026-04-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voicequery',
            new_name='voice_bot_v_user_id_a2c0bb_idx',
            old_name='voice_bot_v_user_id_012345_idx',
        ),
        migrations.RenameIndex(
            model_name='voicequery',
            new_name='voice_bot_v_intent_ca9907_idx',
            old_name='voice_bot_v_intent_012345_idx',
        ),
        migrations.RenameIndex(
            model_name='voicequery',
            new_name='voice_bot_v_session_dff918_idx',
            old_name='voice_bot_v_session_012345_idx',
        ),
    ]
