# Generated by Django 6.0 on 2026-06-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_brand_logo_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dress_length',
            field=models.CharField(blank=True, choices=[('short', 'Short'), ('knee', 'Knee Length'), ('midi', 'Midi / Long Dress'), ('maxi', 'Maxi'), ('full', 'Full Length')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='fit_type',
            field=models.CharField(blank=True, choices=[('slim', 'Slim Fit'), ('regular', 'Regular Fit'), ('relaxed', 'Relaxed & Comfortable Fit'), ('fitted', 'Fitted'), ('straight', 'Straight Fit'), ('flowy', 'Flowy')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='neck_type',
            field=models.CharField(blank=True, choices=[('round', 'Round Neck'), ('square', 'Square Neck'), ('v-neck', 'V-Neck'), ('crew', 'Crew Neck'), ('turtle', 'Turtleneck'), ('boat', 'Boat Neck'), ('halter', 'Halter Neck'), ('cowl', 'Cowl Neck')], max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, help_text='Comma-separated occasions (e.g., Casual Wear, Office Wear, Daily Wear, Outings)', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='pattern',
            field=models.CharField(blank=True, choices=[('solid', 'Solid'), ('printed', 'Printed Ikkat Weave'), ('striped', 'Striped'), ('checkered', 'Checkered'), ('floral', 'Floral'), ('geometric', 'Geometric'), ('embroidered', 'Embroidered'), ('tie-dye', 'Tie-Dye')], max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sleeves_type',
            field=models.CharField(blank=True, choices=[('sleeveless', 'Sleeveless'), ('half', 'Half Sleeves'), ('puff', 'Puff Half Sleeves'), ('full', 'Full Sleeves'), ('three-quarter', 'Three-Quarter Sleeves'), ('cap', 'Cap Sleeves'), ('flutter', 'Flutter Sleeves')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='E.g., Premium Ikkat Cotton', max_length=200),
        ),
    ]
